version: '2'
services:
  percona:
    image: percona/percona-server:5.7.25
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: owa
      MYSQL_USER: owa
      MYSQL_PASSWORD: owdd3223zeg23422656ghdfhgsz
  owa:
    image: minyk/owa:dev
    build:
      context: ./owa
      args:
        OWA_VERSION: 1.6.2
    ports:
      - 8480:80
    environment:
      OWA_PUBLIC_URL: "https://analytics.themightyaxel.de/"
      OWA_DB_HOST: "percona:3306"
